spring.datasource.url=jdbc:mysql://localhost:3306/i94data
spring.datasource.username=root
spring.datasource.password=TigrayAdey19!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
