// store/actions.js
export const authActions = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    LOGOUT: 'LOGOUT',
    SET_USER: 'SET_USER'
};

export const petActions = {
    FETCH_PETS_REQUEST: 'FETCH_PETS_REQUEST',
    FETCH_PETS_SUCCESS: 'FETCH_PETS_SUCCESS',
    FETCH_PETS_FAILURE: 'FETCH_PETS_FAILURE',
    CREATE_PET_REQUEST: 'CREATE_PET_REQUEST',
    CREATE_PET_SUCCESS: 'CREATE_PET_SUCCESS',
    CREATE_PET_FAILURE: 'CREATE_PET_FAILURE',
    UPDATE_PET_REQUEST: 'UPDATE_PET_REQUEST',
    UPDATE_PET_SUCCESS: 'UPDATE_PET_SUCCESS',
    UPDATE_PET_FAILURE: 'UPDATE_PET_FAILURE',
    DELETE_PET_REQUEST: 'DELETE_PET_REQUEST',
    DELETE_PET_SUCCESS: 'DELETE_PET_SUCCESS',
    DELETE_PET_FAILURE: 'DELETE_PET_FAILURE',
    UPDATE_PET_STATUS: 'UPDATE_PET_STATUS',
    SET_FILTERS: 'SET_FILTERS'
};

export const requestActions = {
    CREATE_REQUEST_REQUEST: 'CREATE_REQUEST_REQUEST',
    CREATE_REQUEST_SUCCESS: 'CREATE_REQUEST_SUCCESS',
    CREATE_REQUEST_FAILURE: 'CREATE_REQUEST_FAILURE',
    FETCH_REQUESTS_REQUEST: 'FETCH_REQUESTS_REQUEST',
    FETCH_REQUESTS_SUCCESS: 'FETCH_REQUESTS_SUCCESS',
    FETCH_REQUESTS_FAILURE: 'FETCH_REQUESTS_FAILURE',
    UPDATE_REQUEST_STATUS: 'UPDATE_REQUEST_STATUS'
};