export const SUBMIT_TRAVELER_REQUEST = 'SUBMIT_TRAVELER_REQUEST';
export const SUBMIT_TRAVELER_SUCCESS = 'SUBMIT_TRAVELER_SUCCESS';
export const SUBMIT_TRAVELER_FFAILURE = 'SUBMIT_TRAVELER_FAILURE';
export const FETCH_ANNOUNCEMENT_REQUEST = "FETCH_ANNOUNCEMENT_REQUEST";
export const FETCH_ANNOUNCEMENT_SUCCESS = "FETCH_ANNOUNCEMENT_SUCCESS";
export const FETCH_ANNOUNCEMENT_FAILURE = "FETCH_ANNOUNCEMENT_FAILURE";