
export const I94_ACTION_TYPES = {
  FETCH_RECORDS_REQUEST: 'FETCH_RECORDS_REQUEST',
  FETCH_RECORDS_SUCCESS: 'FETCH_RECORDS_SUCCESS',
  FETCH_RECORDS_FAILURE: 'FETCH_RECORDS_FAILURE',
  
  CREATE_RECORD_REQUEST: 'CREATE_RECORD_REQUEST',
  CREATE_RECORD_SUCCESS: 'CREATE_RECORD_SUCCESS',
  CREATE_RECORD_FAILURE: 'CREATE_RECORD_FAILURE',
  
  UPDATE_RECORD_REQUEST: 'UPDATE_RECORD_REQUEST',
  UPDATE_RECORD_SUCCESS: 'UPDATE_RECORD_SUCCESS',
  UPDATE_RECORD_FAILURE: 'UPDATE_RECORD_FAILURE',
  
  DELETE_RECORD_REQUEST: 'DELETE_RECORD_REQUEST',
  DELETE_RECORD_SUCCESS: 'DELETE_RECORD_SUCCESS',
  DELETE_RECORD_FAILURE: 'DELETE_RECORD_FAILURE',
  
  SET_EDITING_RECORD: 'SET_EDITING_RECORD',
  CLEAR_EDITING_RECORD: 'CLEAR_EDITING_RECORD',
  
  // Address reuse actions
  SET_PREVIOUS_ADDRESS: 'SET_PREVIOUS_ADDRESS',
  USE_PREVIOUS_ADDRESS: 'USE_PREVIOUS_ADDRESS',
  CLEAR_PREVIOUS_ADDRESS: 'CLEAR_PREVIOUS_ADDRESS'
};

export const API_ENDPOINTS = {
  BASE_URL: 'http://localhost:8080/api/i94'
};